Feature/#99
Team-B1ND/dodamdodam-server pull request #103
Opened 2024-08-20 06:56 UTC by GayeongKimm

변경사항 : 
1. 회원가입시 부모연락처를 받도록 수정
2. Admin페이지에서 유저수정 가능하도록

2024-08-20 07:49 UTC, dongchandev commented on dodam-system-domain/dodam-domain-rds/src/main/java/b1nd/dodam/domain/rds/member/entity/Member.java
> +    private String parentPhone;
부모님 번호는 공통 정보가 아니라 학생의 정보이므로 굳이 member 에 추가하기 보다는 student에 추가하는게 맞는 것 같습니다

2024-08-20 07:50 UTC, dongchandev commented on dodam-system-domain/dodam-domain-rds/src/main/java/b1nd/dodam/domain/rds/member/entity/Member.java
> +    private String parentPhone;
@NotNull 도 추가해주세요

2024-08-20 08:00 UTC, dongchandev commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/application/MemberCommandUseCase.java
> +                Teacher teacher = service.getTeacherBy(service.getMemberBy(id));
공통 부분을 switch case 문에 넣을 필요가 없어 보입니다

2024-08-20 08:08 UTC, suw0n commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +
두 줄 공백은 조금 불편하네요 ^^

2024-08-20 08:08 UTC, suw0n commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +    public Response updateInfoForAdmin(@PathVariable String id,
teacher와 student간 공통 정보가 많이 없기 때문에 합쳐서 구현하면 오히려 복잡할 것 같아요. 2개 따로 만드는개 좋아보이네요.

2024-08-20 08:45 UTC, GayeongKimm commented on dodam-system-domain/dodam-domain-rds/build.gradle
> +    implementation 'org.apache.commons:commons-lang3:3.13.0'
StringUtills 사용때문에 의존성 추가했습니다

2024-08-20 08:45 UTC, GayeongKimm commented on dodam-system-domain/dodam-domain-rds/src/main/java/b1nd/dodam/domain/rds/member/entity/Member.java
> +    private String parentPhone;
넵

2024-08-20 08:47 UTC, GayeongKimm commented on dodam-system-domain/dodam-domain-rds/src/main/java/b1nd/dodam/domain/rds/member/entity/Teacher.java
> +    public void updateInfoForAdmin(String tel, String position){
음 admin 메서드를 작성중 중복코드가 있어 함수로 빼 네이밍이 그렇게 됐습니다 수정하겠습니다

2024-08-20 08:48 UTC, GayeongKimm commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +
수정하겠습니다

2024-08-20 08:48 UTC, GayeongKimm commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +    public Response updateInfoForAdmin(@PathVariable String id,
네 분리하겠습니다

2024-08-20 08:48 UTC, GayeongKimm commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/application/MemberCommandUseCase.java
> +                Teacher teacher = service.getTeacherBy(service.getMemberBy(id));
네

2024-08-20 08:48 UTC, GayeongKimm commented on dodam-system-domain/dodam-domain-rds/src/main/java/b1nd/dodam/domain/rds/member/entity/Member.java
> +    private String parentPhone;
네

2024-08-21 00:20 UTC, suw0n requested changes
전반적인 코드 스타일도 한 번 체크해주세요

2024-08-21 00:20 UTC, suw0n commented on dodam-system-domain/dodam-domain-rds/src/main/java/b1nd/dodam/domain/rds/member/entity/Student.java
> +    public void setParentPhone(String parentPhone) {
set or update 하나로 통일해주세요

2024-08-21 00:20 UTC, suw0n commented on dodam-system-domain/dodam-domain-rds/src/main/java/b1nd/dodam/domain/rds/member/entity/Member.java
> +    public void updateInfoForAdmin(String pw, String name, String phone){
ForAdmin을 지우는게 좋아보여요. 회원 정보 수정 API가 추가되면 이 메서드를 사용할 것 같아요.

2024-08-21 00:20 UTC, suw0n commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +    public Response updateTeacherForAdmin(@PathVariable String id, @RequestBody UpdateTeacherForAdminReq req){
학생, 선생님 정보를 본인이 직접 수정하는 API가 필요한 것 같아요. 관리자가 회원 정보를 수정하는 것은 조금 이상하네요.

2024-08-21 00:57 UTC, GayeongKimm commented on dodam-system-domain/dodam-domain-rds/src/main/java/b1nd/dodam/domain/rds/member/entity/Member.java
> +    public void updateInfoForAdmin(String pw, String name, String phone){
아이들이랑 얘기했을때 유저쪽에서 부모전화번호 수정을 막고 어드민에서만 유저수정을 하자고 하였습니다

2024-08-21 01:26 UTC, GayeongKimm commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +    public Response updateTeacherForAdmin(@PathVariable String id, @RequestBody UpdateTeacherForAdminReq req){
학생정보를 수정하는 api는 이미 존재하고, 선생님 정보 수정 api는 현재 이슈에서 작업하기에 연관성이 없어 다른 이슈에서 개발하려 했습니다.
관리자가 회원정보를 수정하는 이유는 비밀번호를 까먹거나 부모 전화번호가 옳지 않을때 db에 직접 수정것이 아닌 admin페이지에서 수정이 가능하도록 하기위해 만들었습니다.

2024-08-21 08:08 UTC, suw0n commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +    public Response updateTeacherForAdmin(@PathVariable String id, @RequestBody UpdateTeacherForAdminReq req){
회원 정보의 주인은 회원이기 때문에 관리자에게 회원 정보를 수정할 수 있는 권한을 주는 것은 잘못된 것 같아요. 정보가 잘못된 경우일 때는 회원 본인이 수정할 수 있도록 가이드하는 것이 맞지 않을까요?

2024-08-21 08:11 UTC, suw0n commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +    public Response updateTeacherForAdmin(@PathVariable String id, @RequestBody UpdateTeacherForAdminReq req){
학생이 관리자에게 비밀번호를 변경해달라고 요청하고, 관리자가 비밀번호를 수정한 후 다시 학생에게 알려줘야하는데 학생이 그 시간동안 서비스를 이용하지 못할 뿐더러 관리자가 비밀번호를 알게되는 문제가 발생할 수 있을거 같아요.

2024-08-21 09:26 UTC, GayeongKimm commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +    public Response updateTeacherForAdmin(@PathVariable String id, @RequestBody UpdateTeacherForAdminReq req){
회원 비밀번호 변경은 회원이 비밀번호를 까먹었을때 저희에게 재 설정 요청이 많이 와서 만들어 놓은 api입니다. 
예를들어 회원이 비밀번호 변경 요청이 오면 관리자는 12345678로 비밀번호를 변경하고 회원이 그것을 통해 로그인 후 비민번호 변경을 다시 할 수 있도록 설계했었습니다.
평소에는 해시변환 작업과 db에 수동으로 초기 비밀번호 설정을 하는것이 불편해 만들었습니다.

또 8기와 얘기했을때 상벌점 문자가 부모님에게 가는것이 부끄러워 일부러 다른 전화번호를 넣을 가능성이 너무 크다는 이야기 때문에 관리자 페이지에서 수정이 가능하도록 작업했었습니다.
유저쪽에서도 정보변경이 가능하지만 부모 전화번호 변경만 되지 않도록 막아놓았는데 가능하게 하도록 변경과 관리자가 회원정보 변경을 불가능하게 하도록 변경해야 할까요?

2024-08-21 12:04 UTC, suw0n commented on dodam-application/dodam-rest-api/src/main/java/b1nd/dodam/restapi/member/presentation/MemberController.java
> +    public Response updateTeacherForAdmin(@PathVariable String id, @RequestBody UpdateTeacherForAdminReq req){
일단은 이대로 진행하고, 새 이슈파고 좀 더 얘기해봐요.

2024-08-24 12:04 UTC, suw0n approved these changes

2024-08-24 12:06 UTC, suw0n commented
학생 회원가입할 때, 부모님 전화번호도 받게하는 부분이랑 관리자가 부모님 전화번호를 변경하는 부분만 남기고 머지한 후에 비밀번호 재설정 같은 부분은 다른 이슈에서 작업하는게 좋을 것 같아요.

2024-09-03 11:09 UTC, suw0n commented
👏👏👏

2024-09-03 11:09 UTC, merged